### ISSUE TITLE
More idiomatic representation of variants

### ISSUE THREAD

**Issue by jchavarri** [cristianoc/genType#112]
Right now, variant types are exposed as union types made from individual opaque types.

While opaque types work, they make it harder for consumers to work with values from these types. In both [Flow](https://flow.org/en/docs/lang/refinements/) and TypeScript, type refinements (aka "type guards" in [TypeScript literature](https://www.typescriptlang.org/docs/handbook/advanced-types.html)) is commonly used to narrow down an individual type from the union.

With the current approach, based on BuckleScript representation of an array with a `tag` property attached to it, there is no way for Flow or TS consumers to work with values from the union type resulting from the original type.

I wonder if there could be a way –maybe optional?– in which variants could be converted into JavaScript objects that shared a common property `tag` (the discriminant) with another property `value` that contained the fields inside the variant.

For example:

```reason
type action = Foo(string) | Bar(int, int); 
```

would be converted into the following JS/Flow code (similar for TS):

```js
export type ActionFoo = {| tag: 'foo', value: [string] |};

export type ActionBar = {| tag: 'bar', value: [number, number] |};

export type action =
  | ActionFoo
  | ActionBar;
```

The downside of this approach is that it'd require converting back and forth between both representations, with the inherent complexity.

**Comment by cristianoc** [comment]
Sounds like a good direction to explore. Also, it might be a non-breaking change as strictly more would be revealed of the runtime representation (while changing it).

**Comment by cristianoc** [comment]
@jchavarri expanding the proposal further, where there is a single Enum representation on the JS side.  This can be generated either from a normal variant, or from a polymorphic variant, and there's no way to tell from the JS side. The difference in practice become the typing on the Reason side: more static or more dynamic.

Here are possible steps to get there:
1) Expand the current treatment of Enums to allow an arbitrary number of cases carrying payloads of arbitrary type. If there is at most one case with payload, and that payload is of object type, then use the current unboxed representation of Enums.
Otherwise the default representation of Enums is the bs representation of polymorphic variants.
2) Track in the Enum type whether the origin is a variant or a polymorphic variant. The runtime representation will be the same, but the conversion functions will be different:
- poly variants with one payload variant of object type: unboxing conversion.
- other poly variants: no conversion.
- variants: always convert between bucklescript's internal representation of variants. A conversion is required for the unboxed single variant case, as well as for the general case.

**Comment by jchavarri** [comment]
@cristianoc I'm curious about the differences between polymorphic and regular variants from the Flow / TypeScript side. What implications are you foreseeing, supposing the different values from the types are "read only" on the Flow/TS side? What I mean is that regardless any additional operations over these variants that could be done in Flow/TS, when values are passed back to Reason, they would need to be in the original types, so the Reason typing rules would always apply.

Or is there a case where Flow/TS could break the typing rules for variants?

**Comment by cristianoc** [comment]
@jchavarri the idea would be to represent polymorphic and regular variants in exactly the same way on the JS side, so there would be no difference. The difference would only be on how things are treated on the Reason side. Incidentally, one could even translate between regular and polymorphic Reason variants by going through the identity function on the JS side.

**Comment by cristianoc** [comment]
Part 2: use Enums for ordinary variants too, is in https://github.com/cristianoc/genType/pull/122.

**Comment by cristianoc** [comment]
The major change to the representation of ordinary variants and polymorphic variants are now in release 2.0.0.

**Comment by jchavarri** [comment]
Awesome!!
