### ISSUE TITLE
Simplify FFI declarations

### ISSUE THREAD

**Issue by cem2ran** [cristianoc/genType#117]
While experimenting with replacing existing bucklescript bindings with genType, I've observed a great reduction in LOC w.r.t consuming react.js components, but an overall increase when consuming methods and objects due to the boilerplate involved in declaring such bindings.

One such example:
```ocaml
[@genType.import "expo"]
[@bs.as "Asset.downloadAsync"]
[@bs.module "./Asset.gen"]
external downloadAsync : (t, unit) => Js.Promise.t(unit) = "";

[@genType.import "expo"]
[@genType.as "Asset.loadAsync"]
[@bs.module "./Asset.gen"]
external loadAsync :
  array(BsReactNative.Packager.required) => Js.Promise.t(unit) =
  "";

[@genType.import "expo"]
[@genType.as "Asset.fromModule"]
[@bs.module "./Asset.gen"]
external fromModule : BsReactNative.Packager.required => t = "";
```
Quite a bit of repetition. 

Could we instead make use of the OCaml module system to express this, like so?
```ocaml
[@genType.import "expo"]
[@bs.module "./Asset.gen"]
module Asset = {
  external downloadAsync : (t, unit) => Js.Promise.t(unit) = "downloadAsync";

  external loadAsync :
  array(BsReactNative.Packager.required) => Js.Promise.t(unit) =
  "loadAsync";

  external fromModule : BsReactNative.Packager.required => t = "fromModule";
}
```
ideally the assignment would be optional and picked up from the ffi method name:

```ocaml
external downloadAsync : (t, unit) => Js.Promise.t(unit) = "";

(* if rename is needed you could specify it: *)
external download : (t, unit) => Js.Promise.t(unit) = "downloadAsync";
```

I believe you also have mentioned this, but having the [@bs.module ___] declaration be optional would also help, by for example making it default to module name followed by, '.gen'.

**Comment by cristianoc** [comment]
@cem2ran these are good questions.

First unpacking the various parts of:
```reason
[@genType.import "expo"]
[@genType.as "Asset.loadAsync"]
[@bs.module "./Asset.gen"]
external loadAsync :
  array(BsReactNative.Packager.required) => Js.Promise.t(unit) =
  "";
```

There are 2 annotations for genType and 1 for bucklescript.
The annotation for bucklescript `[@bs.module "./Asset.gen"]` is attached to an `external declaration` and tells bucklescript where to find the value in the file generated from genType. A consequence of that, is that this annotation must be present for each `external` declaration of a value. This is the "bucklescript independence tax", paid because genType runs **after** bucklescript is done. In future, one could embed genType inside bucklescript, and make these annotations unnecessary.

The only way to use a single `[@bs.module "./Asset.gen"]` would be to have a single `external` with all the values. Unfortunately, a module cannot be declared as `external`, it's just not part of the language. One could use a first-class module, by declaring the module type, then declare it as external, finally unpack it unto a module for use by people. That's a rather heavy weight way to go in my opinion, though technically I think it seems doable.

The part where one could try to avoid duplication, as things stand right now, is the `[@genType.import "expo"]` part, as well as the `"Asset."` part of the information. To achieve that, something like this could be supported:
```reason
[@genType.import "expo"]
[@genType.as "Asset"]
module Asset = {
  [@bs.module "./Asset.gen"]
  external downloadAsync : (t, unit) => Js.Promise.t(unit) = "";

  [@bs.module "./Asset.gen"]  
  external loadAsync : array(BsReactNative.Packager.required) => Js.Promise.t(unit) = "";

  [@bs.module "./Asset.gen"]  
  external fromModule : BsReactNative.Packager.required => t = "";
};
```

In fact, the annotation `[@genType.as "Asset"]` could probably be omitted, as one can just pick up the name of the module. One would need it for nested paths, as in e.g. `[@genType.as "Some.Path.To.Value"]`.

Now moving to more speculative, longer term design. In addition to moving genType inside bucklescript, one could make FFI first-class in the language. So one can imagine something looking like this:
```ts
import loadAsync : array(BsReactNative.Packager.required) => Js.Promise.t(unit)
from "./Asset.gen//Asset";
```
and the whole thing as:
```ts
import module Asset = {
  let downloadAsync : (t, unit) => Js.Promise.t(unit);

  let loadAsync : array(BsReactNative.Packager.required) => Js.Promise.t(unit);

  let fromModule : BsReactNative.Packager.required => t;
} from "./Asset.gen//Asset";
```

**Comment by cem2ran** [comment]
Thank you for the breakdown. I understand the challenges much better now. 

As a short-medium term solution I would be more than happy to have the solution you mentioned:

```ocaml
[@genType.import "expo"]
[@genType.as "Asset"] (* I wouldn't mind being explicit if I only have to declare it once for the module and it's externals (less magic/implicitness) *)
module Asset = {
  [@bs.module "./Asset.gen"]
  external downloadAsync : (t, unit) => Js.Promise.t(unit) = "";

  [@bs.module "./Asset.gen"]  
  external loadAsync : array(BsReactNative.Packager.required) => Js.Promise.t(unit) = "";

  [@bs.module "./Asset.gen"]  
  external fromModule : BsReactNative.Packager.required => t = "";
};
```

I guess we could also implement the import in user land and go the module type route and declare a module type which then is preprocessed to produce the appropriate externals?

```ocaml
[@genType.import "expo"]
[@genType.as "Asset"]
module type Asset = {
  let downloadAsync : (t, unit) => Js.Promise.t(unit) = "";

  let loadAsync : array(BsReactNative.Packager.required) => Js.Promise.t(unit) = "";

  let fromModule : BsReactNative.Packager.required => t = "";
};
```
This would desugar to the above, or the current more verbose (working) solution.
Do you think this is a viable path to explore?

This is just me being nitpicky, but could we also do `[@genType.import ("expo", "Asset")]`? This is just me trying to decrease the amount of new things you have to learn going from bucklescript to genType. I believe you can do this in bucklescript with bs.module.

**Comment by cristianoc** [comment]
In case of module type the tricky part would be consumption: the declaration of an extern of  first-class-module type, and the unpacking to consume it:
```reason
[@bs.module "./Asset.gen"] external asset: (module Asset) = "";

module Asset = (val asset);

let downloadAsync = Asset.downloadAsync;
```

The declaration `[@genType.import ("expo", "Asset")]` sounds like a good direction to explore, to reduce cognitive load as you've indicated.

**Comment by cristianoc** [comment]
@cem2ran thinking of one suggestion in particular, perhaps it makes sense that, in general, every occurrence of
```reason
[@genType.import "foo"] [@genType.as "Caffe.bar"]
```
should instead be written as
```reason
[@genType.import ("foo", "Caffe.bar")]
```.

**Comment by cristianoc** [comment]
What it means, is that this would be doable once genType is part of bucklescript, but not before.

**Comment by cem2ran** [comment]
Ok. I'll have to scratch my head a little and look further into this. So ppx extensions that you would normally declare under bsconfig's "ppx_flags" are run as a part of the bucklescript/ocaml compilation process (and prior to js compilation) and genType is run after this, but before js compilation? (Sorry for not using the appropriate compiler terms, but I hope you understand my statement)

If that is the case, I understand it, but still fail to understand why this wouldn't be possible with lets say another @ffi.import extension point that does the mentioned; purely syntactic transform of the module signature AST to a module containing externals with appropriate genType.* annotations.

Do projects like (Typpx)[https://bitbucket.org/camlspotter/typpx] change anything w.r.t: _"There’s no support for typed ppx transformations in the compiler."_?

Looking forward to genType being a part of Bucklescript itself! I'll experiment a little with my ideas to further my understanding of PPXs.

**Comment by cristianoc** [comment]
PPXs run before type checking. Bucklescript runs after typechecking. genType runs after bucklescript is done, and produces additional js files.

If a transformation is “black box”, such as copying things around, a bit like a regexp but for the AST, chances are it’s doable as a PPX.

Your transformation could fall into this category. Eg adding “Filename.gen” definitely does.

In contrast, genType itself does not, as it needs Eg to inspect inferred types.

**Comment by cristianoc** [comment]
Happy to revive the conversation if we have fresh ideas of what features to add.
