### ISSUE TITLE
Add support for Belt.Result

### ISSUE THREAD

**Issue by aurerua** [cristianoc/genType#131]
# How to reproduce

Use Belt.Result, for instance:

```reason
type error =
  | NoAuthToken
  | UndefinedError;

[@genType]
let getToken = (token) =>
  switch (token) {
  | Some(token) => Belt.Result.Ok(token)
  | None => Belt.Result.Error(NoAuthToken);
  };
```

genType creates a `gen.tsx` file that contains this import:
```js
import {Result_t as Belt_Result_t} from './Belt.gen';
```

This gives but this Typescript error:
```
Cannot find module './Belt.gen'.
```

**Comment by cristianoc** [comment]
@aurerua I'm considering this issue, as well as https://github.com/cristianoc/genType/issues/132.
There's the question about a general pattern for libraries, and whether a general mechanism could be provided to ask also the next similar questions going forward.

Before doing that, I'd like to know a little more about the use case.
For this one, one can get an idea of how things could look like by e.g. using:
```
module MyResult = {
  [@genType]
  type t('a, 'b) =
    | Ok('a)
    | Error('b);
};

[@genType]
let getMyToken = token =>
  switch (token) {
  | Some(token) => MyResult.Ok("token:" ++ token)
  | None => MyResult.Error(42)
  };
```
to see what the JS code would look like.

Is the idea to access this specific type from JS?
```
export type MyResult_t<a,b> = 
  | { tag: "Ok"; value: a }
  | { tag: "Error"; value: b };

```
i.e. construct/destruct values using tag and value? Or it the idea to use this as an opaque type so that the JS side does not need to know the internal representation but will just pass these values back to functions coming from Reason?

**Comment by cristianoc** [comment]
For promises: typing promises is kind of a known challenge. And I was wondering if the assumption is that there are typed promises on the JS side, and one would like to conform to them, or whether the idea is to just use an opaque type on the JS side.

**Comment by aurerua** [comment]
@cristianoc Thank you for the MyResult module example. In the current use case, I am not sure if using an opaque type woud be doable/suitable because the point of using Belt.Result is to know which type is coming out.
