### ISSUE TITLE
Add support for Js.Promise

### ISSUE THREAD

**Issue by aurerua** [cristianoc/genType#132]
# How to reproduce

Use `Js.Promise`, for instance:

```reason
[@genType]
let selectFolder = (path) => {
  Js.Promise.(
    fetchFolder(path)
    |> then_(
         //...
       )
    |> ignore
  );
};
```

genType creates a `gen.tsx` file that contains this import:
```js
import {Promise_t as Js_Promise_t} from './Js.gen';
```

This gives but this Typescript error:
```
Cannot find module './Js.gen'.
```

**Comment by Yakimych** [comment]
@cristianoc I've read the [comment](https://github.com/cristianoc/genType/issues/131#issuecomment-457171134) in the referenced issue, but I am not sure I understand completely (regarding a Promise on the JS side and opaque type).

There is a `Promise` type in TS (`Js.Promise` in Reason), and if there is a way to generate a `.gen.tsx` file using `Promise`, instead of `Js_Promise_t`, that would solve the issue. I tried replacing it manually in the `.gen.tsx` file (for testing purposes) and the TypeScript code picked it up without a problem.

With the current error, I get `any` in TypeScript 😢

**Comment by nhducit** [comment]
'./JS.gen' is a shim file. I think you can try this:

add `JS.shims.ts` file to `shims` folder.

```ts
export type Promise_t = Promise
```

https://github.com/cristianoc/genType/issues/150

**Comment by nhducit** [comment]
this is the example:
reason:
```
[@genType]
let selectFolder = path => {
  let myPromise = Js.Promise.make((~resolve, ~reject) => resolve(. 2));
  path |> Js.log;
  myPromise
  |> Js.Promise.then_(value => {
       Js.log(value);
       Js.Promise.resolve(value + 2);
     })
  |> Js.Promise.then_(value => {
       Js.log(value);
       Js.Promise.resolve(value + 3);
     })
  |> Js.Promise.catch(err => {
       Js.log2("Failure!!", err);
       Js.Promise.resolve(-2);
     });
};
```

.gen.ts file
```js
export const selectFolder: <T1>(_1:T1) => Js_Promise_t<number> = decodeBS.selectFolder;
```

**Comment by Yakimych** [comment]
@nhducit that seems to have gotten the job done, thanks!

Does it mean that this issue is not really necessary and can be closed?

**Comment by cristianoc** [comment]
First-class support for promises:
https://github.com/cristianoc/genType/commit/fd5d54b9d032dc820e612831d2c6bda44f7865b9
