### ISSUE TITLE
Type constraints broke generic types

### ISSUE THREAD

**Issue by meafmira** [cristianoc/genType#154]
For example:
```
[@genType]
type decorator('a, 'b) = 'a => 'b constraint ('a, 'b) = (_ => _, _ => _);
```
->
```
export type decorator = (a) => b;
```

so `a` and `b` are undefined

**Comment by cristianoc** [comment]
This is handled in https://github.com/cristianoc/genType/commit/1f75f430b77c6110d46789ca82a658b77b4f9c66.
Turns out type constraints were propagated into the type parameters, so the original variable names `'a` and `'b` were not found. Instead, in the typedtree part of the AST, the type parameters were unchanged.

**Comment by cristianoc** [comment]
The constraints are simply ignored on the JS side, as it's unclear how one could represent them. So the type is exported as if there were no constraints.

**Comment by cristianoc** [comment]
In release https://github.com/cristianoc/genType/releases/tag/v2.12.0.
