### ISSUE TITLE
Error recursive function/types

### ISSUE THREAD

**Issue by tatchi** [cristianoc/genType#156]
Hello,

I've created this function is ReasonML:

```typescript
[@gentype]
type operation =
  | Add(operation, operation)
  | Sum(operation, operation)
  | Int(int);

[@gentype]
let rec calc = operation =>
  switch (operation) {
  | Add(op1, op2) => calc(op1) + calc(op2)
  | Sum(op1, op2) => calc(op1) * calc(op2)
  | Int(number) => number
  };
```
with the types from `gentype`:

```typescript
export const calc: (_1:operation) => number = function _(Arg1: any) {
  const result = 
/* WARNING: circular type operation. Only shallow converter applied. */
  DemoBS.calc(Arg1.tag==="Add"
    ? CreateBucklescriptBlock.__(0, Arg1.value)
    : Arg1.tag==="Sum"
    ? CreateBucklescriptBlock.__(1, Arg1.value)
    : CreateBucklescriptBlock.__(2, [Arg1.value]));
  return result
};
```

But when I try to use the generated function in a `ts` file:
```typescript
import { operation, calc } from "./Demo.gen";

const myOp: operation = {
  tag: "Add",
  value: [
    { tag: "Sum", value: [{ tag: "Int", value: 2 }, { tag: "Int", value: 3 }] },
    { tag: "Int", value: 5 }
  ]
};

console.log(calc(myOp));
```

I get the following error:

```  
switch (operation.tag | 0) {
                    ^
TypeError: Cannot read property 'tag' of undefined
```

I've seen that there's some indication about recursive types in the readme but I'm not sure to understand everything (I'm still new in the ReasonML world). Therefore, I'm not even sure that this case should be supported but still wanted to report it in case of...

Sorry if it was not helpful and in this case feel free to close the issue.

**Comment by cristianoc** [comment]
@tatchi thank you for opening the issue.
This is a good question to ask.

The representation of variants requires conversion when mapping between the Reason (arrays with specific tags) and JS (objects) representations. The conversion functions are generated automatically in normal cases.

Let's now consider the case of recursive data types. The question is what the conversion functions should do. To be correct, the conversion should walk the data structure inductively, and convert nodes along the way. So at the very least, there would be a traversal cost to be paid every time the JS/Reason boundary is crossed.
In reality things are a bit more complicated than that. There are several possible ways of converting a recursive data structure. For example, what about sharing? If the conversion functions respect sharing, then the conversion code will be more complicated and will have to remember what was shared in the original data. Otherwise, a linear data structure could become exponentially larger after conversion.
Another question is: what about cyclic structures? If one wants to handle those, then again the conversion would need to be further complicated, or else fall into some infinite loop.

The current state is that if cycles are detected in the type declaration, the conversion is not performed. And that's what you've been observing.

Before making a suggestion for this specific issue, a question: what is the intended use case of exporting the recursive data structure to JS?
Asking as one way to go about that, is to define an abstract data type, where the internal details of the implementation are not exposed. This would often be the choice even if the consumer were other Reason code.

But, I'd like to know more about the context here.

(This answer is intentionally a little lengthy, so it can be referred to later from the README, as a form of extended documentation).

**Comment by tatchi** [comment]
Hi @cristianoc, thanks for your response.

> Before making a suggestion for this specific issue, a question: what is the intended use case of exporting the recursive data structure to JS?
> Asking as one way to go about that, is to define an abstract data type, where the internal details of the implementation are not exposed. This would often be the choice even if the consumer were other Reason code.
> 
> But, I'd like to know more about the context here.

There's no specific context there, I was just playing a little bit with the library just for fun. I don't really have experience in building application with ReasonML so I probably made things that don't have any sense.

However, I'm not sure I've really understood your solution. Could you share an example of how you would do it?

**Comment by cristianoc** [comment]
@tatchi one way to go is to export the type as opaque:
```reason
[@gentype.opaque]
type operation =
  | Add(operation, operation)
  | Sum(operation, operation)
  | Int(int);
```

and export some construction functions:
```reason 
[@genType]
let int = (i) => Int(i);

[@genType]
let add = (x,y) => Add(x,y);

[@genType]
let sum = (x,y) => Mul(x,y);
```

In this way, no deep conversion is needed (in fact there's no conversion at all), and values can be constructed from the JS side.

**Comment by tatchi** [comment]
@cristianoc Thanks for the solution, it works perfectly (just had to find another name for `int`) 👍
