### ISSUE TITLE
Prop rename [@genType.as] not working with new Reason React 0.7.0

### ISSUE THREAD

**Issue by peterpme** [cristianoc/genType#194]
Hey,

We're upgrading everything to `reason-react@0.7.0` and our `[@genType.as]` are failing. 

```
reason-react: 0.7.0
bs-platform: 5.0.4
gentype: 2.23.0
```

Previous way we were doing this (worked)

```reason
module Link = {
  [@bs.module "react-router-dom"] external link: ReasonReact.reactClass = "Link";

  [@bs.deriving abstract]
  type jsProps = {
    to_: string,
    replace: bool,
    className: string,
  };

  let make = (~to_, ~className=?, ~replace=false, children) =>
    ReasonReact.wrapJsForReason(
      ~reactClass=link,
      ~props={"to": to_, "replace": replace, "className": className},
      children,
    );
};
```

Here is how we're doing this now:

### GenTypeTest.re

```reason
[@genType.import ("react-router-dom", "Link")] [@react.component]
  external make:
    (~replace: bool=?, ~className: string=?, ~children: React.element) => [@genType.as "to"] (~to_: string) =>
    React.element = "";
```

### GenTypeTest.bs.js

```js
// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as GenTypeTestGen from "./GenTypeTest.gen";

var make = GenTypeTestGen.make;

export {
  make ,
  
}
/* make Not a pure module */
```

### GenTypeTest.gen.js

```js
/** 
 * @flow strict
 * @generated
 * @nolint
 */
/* eslint-disable */

// flowlint-next-line nonstrict-import:off
import {Link as makeNotChecked} from 'react-router-dom';

// In case of type error, check the type of 'make' in 'GenTypeTest.re' and 'react-router-dom'.
export const makeTypeChecked: ({|
  +replace?: boolean, 
  +className?: string, 
  +children: React_element, 
  +to_: string
|}) => React_element = makeNotChecked;

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make: mixed = makeTypeChecked;

// flowlint-next-line nonstrict-import:off
import type {element as React_element} from '../../src/shims/ReactShim.shim';
```

Everything compiles, but when my javascript runs, I get `The to prop is required` (which is a react-router method when `to` isn't matched.

Any help would be appreciated. Thank you

**Comment by peterpme** [comment]
It's worth noting this works in JAVASCRIPT, when I import GenTypeTest, but it DOES NOT work on the Reason side when I use `to_`

**Comment by cristianoc** [comment]
@peterpme thanks for the report!
Indeed, it looks like `@genType.as` is not picked up in conjunction with `[@react.component]`.
While investigating what happens to the attribute when it goes through the PPX transform, there's a fortunate coincidence that allows a workaround:
The PPX generates an object type, and object types obey bucklescript's marshaling rules, so one can use this as a workaround: `(~to__: string)` without `genType.as` annotation.
Would you give it a try?

**Comment by cristianoc** [comment]
FYI @rickyvetter

**Comment by peterpme** [comment]
@cristianoc of course, thank you for your quick reply. It's always appreciated.

I will try this now and get back to you in a minute :smile:

**Comment by peterpme** [comment]
@cristianoc is this what you mean? Just to make sure I'm testing the right thing.

```reason
[@genType.import ("react-router-dom", "Link")] [@react.component]
  external make:
    (~replace: bool=?, ~className: string=?, ~to__: string, ~children: React.element) =>
    React.element = "";
```

Working results should be below, correct?

Javascript: `<Link to="/apps">Test</Link>`
Reason: `<Link to__="/apps">"Test"->React.string</Link>`

**Comment by cristianoc** [comment]
@peterpme yes that's the expectation.

**Comment by peterpme** [comment]
This does work! Should I consider this a workaround that we will ultimately go back to and fix or can I use and apply this to things like `match` as well?

Thank you :smile:

**Comment by cristianoc** [comment]
@peterpme after doing some more investigation, here are some thoughts.

First, since the hooks PPX converts named args to objects, and bucklescript has marshaling rules for object fields, it follows that the marshaling rules must be respected as that's what the runtime representation is. So the first comment is that one can rely on those rules, and it's not just a temporary workaround which would disappear tomorrow.

Also, there are marshaling rules for keywords, so `_to` maps to `to` and `_match` maps to `match`. Here are the rules:
```
     Remove trailing "__" if present.
     Otherwise remove leading "_" when followed by an uppercase letter, or keyword.
```

Currently, there is no support for `genType.as` on `Js.t(-)` objects. One reasons is that annotations for object types can be fiddly (easy to support when the type is declared separately, but it gets difficult/impossible when the type is just used inline).

I'm currently tempted to provide support for the marshaling rules when defining normal functions too, in addition to the case of functional components. Effectively, turn the workaround on its head and make it the way one would have written normal functions to begin with, so when writing functional components there are no surprises. That would remove one inconsistency. Also, `genType.as` itself is quite fiddly for functions already, e.g. with the weird formatting of the argument list.

**Comment by cristianoc** [comment]
The marshaling convention suggested here is now the recommended way to rename normal functions, function components, as well as object fields.
