### ISSUE TITLE
Cooperating with genType-powered dependencies

### ISSUE THREAD

**Issue by wokalski** [cristianoc/genType#242]
I have three packages:

- Client
- Server
- Common

All of them use `genType` for generating TS files. When I use something from `Common.Something` module (i.e. from 'Something.re' in the `Common` package) `genType` doesn't pick up correct definitions from the Common's package modules (i.e. I'd expect it to import refs from `Common/Something.gen`).

I realise it's a complex issue at the intersection of package management and buckle script itself (especially with namespaces enabled).

What's the best approach to take here? I'm currently creating and manually maintaining shims for the Common package which is turning out not to be that bad. I also needed to create `index.ts` inside Common package to reexport all generated definitions.

**Comment by cristianoc** [comment]
@wokalski do you have any suggestions on how to go about this?
I guess somewhere, knowledge of all the packages involved is required.

**Comment by wokalski** [comment]
My line of thinking begins with BuckleScript; the dependency structure between generated TS files mirrors to the structure (and locations) of dependencies between Reason/OCaml files. I'm not familiar with neither internals of BuckleScript or genType but there is the knowledge of all packages involved in the BuckleScript's build environment.

**Comment by cristianoc** [comment]
Wondering if this is somehow related: https://github.com/BuckleScript/bucklescript/pull/3803

**Comment by thislogancall** [comment]
@wokalski How are you accomplishing this? I'm working on a project with the same structure (Common pkg used by server and client)

The one thing I'm not able to figure out is when the server or UI *.re files are generated, all the imports that use my common package end in `.gen` instead of `.shim`. Example: `import {Company_companyPlanIndex as Universal_Company_companyPlanIndex} from '../../src/shims/Universal.gen';`

I've tried various settings in `bs-config.json` to fix this but can't find a solution.

**Comment by thislogancall** [comment]
NM Noob moment. Had my shims object in the `bsconfig` outside of `gentypeconfig`. For anyone who runs into this you can set a custom path instead of just a name for where your shim is. Example:
```json
"shims": {
      "Universal": "./src/shims/Universal.shim.ts"
    }
```

**Comment by cristianoc** [comment]
What happens even before running genType? Are the cross-references generated correctly by bucklescript, and how?

**Comment by thislogancall** [comment]
I'm assuming you're referring to using values (not types from my "common" package).

If the project that's dependent on the "common" package uses a value from it, bucklescript generates the import correctly. Example (Bcu is my 

```javascript
var Company$Bcu = require("bcu/src/Company.bs.js");
```

**Comment by wokalski** [comment]
I took another approach, I created shim files which I maintain manually which just reexport stuff from genotyped files in another package. It's not ideal I admit.

**Comment by thislogancall** [comment]
That makse sense. I still needed a shim but since I re-exported everything from the common package index file, my shim looked like this: 
```typescript
export * from "common"
```

**Comment by cristianoc** [comment]
@thislogancall is `Bcu` in `node_modules`?

**Comment by thislogancall** [comment]
Yes

**Comment by cristianoc** [comment]
@thislogancall  OK then  I did not understand the context well enough.
It might be possible for genType to read the relevant part of bsconfig and look for files in the appropriate place in node_modules.

**Comment by cristianoc** [comment]
There's a PR now: https://github.com/cristianoc/genType/pull/301.
The convo can be continued there.

**Comment by cristianoc** [comment]
@thislogancall let me know if this is in line with what you need:
https://github.com/cristianoc/genType/pull/301/files#diff-4efc27d1cbc4824c8201fe740f82031cR11

**Comment by cristianoc** [comment]
This has an example of creating a library and using its types: https://github.com/cristianoc/genType/pull/301.

**Comment by thislogancall** [comment]
@cristianoc Yes, I believe it does. Once this is in the latest release I can confirm.

**Comment by thislogancall** [comment]
@cristianoc I believe this is only partially resolved. I still need to implement a shim file, but now I have to do it for each module within the `universal` package instead of the `universal` as a whole.

For instance, the following code is generated code from the UI. The source file for this is a `.re` and uses the `universal` package.

```typescript
import {authedCompany as Company_authedCompany} from './Company.gen';
```

Really I would imagine that it would be importing it like this:

```typescript
import {authedCompany as Company_authedCompany} from "@some_company/universal/lib/Company.gen"
```

Again, the `universal` package is written in Reason with genType. The UI is partially in Reason right now and also using genType. Let me know if more info would help!

The part that did seem to get fixed — genType previously was importing it like this so i now don't have to export `authedCompany` a second time as `Company_authedCompany`:
```
import {Company_authedCompany as Bcu_Company_authedCompany} from '...';
```

**Comment by thislogancall** [comment]
@cristianoc Actually, I thought i'd be able to setup a shim for the individual modules but it seems shims for the `universal` package that's also created with Re/gentype don't seem to be registering.

I'm trying to setup a shim for this to use the npm package:
```typescript
import {authedCompany as Company_authedCompany} from './Company.gen';
```

My bsconfig:

```json
{
"gentypeconfig": {
    "exportInterfaces": false,
    "language": "typescript",
    "importPath": "absolute",
    "module": "commonjs",
    "debug": {
      "all": false,
      "basic": false
    },
    "shims": {
      "Js": "Js",
      "Company": "Company",
      "User": "User",
      "ReactDOMRe": "ReactDOMRe",
      "ReactEvent": "ReactEvent",
      "Axios": "Axios",
      "Future": "Future",
      "Axios_types": "Axios",
      "Belt": "Belt",
      "Css": "Css",
      "ReasonReactRouter": "ReasonReactRouter"
    }
  },
  ...
}
```

Shim (Company.shim.ts)
```
export * from "@bidchuck/universal/lib/Company.gen"
```

**Comment by cristianoc** [comment]
@thislogancall I'd like to actually reduce the use of shims -- possibly eliminate them eventually.
E.g. if your code is in Reason, then you should not need shims.

**Comment by thislogancall** [comment]
Right, agreed, but the reason for the need here is because genType is generating the import statement incorrectly. It's looking for the `Company` module in the current directory when it should be pulling from an NPM package. Any suggestions?

**Comment by cristianoc** [comment]
@thislogancall what npm package, and do you have control over the package?

I had a little test where it was importing from eg bs-fetch, though of course it could not find the .gen file there, but the reference was correct.

**Comment by thislogancall** [comment]
@cristianoc It's the `universal` package I've been referencing this issue. It's a package in a private repository and yes I have control over it.

**Comment by cristianoc** [comment]
@thislogancall I think a good goal is to:
1) run genType on `universal`, and publish it so that it has `.gen.ts` files in addition to `.bs.js` ones.
2) reference it from `bs-dependencies`, also notice you need to opt-in by using `use-bs-dependencies` from any package using `universal`, see release notes https://github.com/cristianoc/genType/releases/tag/v3.4.2.

This "might" work (these are all new feature hence the "might").

Eventually I want to remove the opt-in part. It's there just to be on the safe side for now.

**Comment by thislogancall** [comment]
@cristianoc Perfect. I had done everything except add `"use-bs-dependencies": true` to my `gentypeconfig`. Everything is working as expected now, thank you.

**Comment by cristianoc** [comment]
@thislogancall oooh this is great!
I should document this, make the feature visible, and remove the opt-in part.
